name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: docker build --plattform linux/arm64 -t runner-image .

    - name: Tagging
      run: docker tag runner-image bugfrei/github-runner:latest

    - name: Push to Docker Hub
      run: docker push bugfrei/github-runner:latest
      
